apiVersion: v1
kind: Service
metadata:
  name: jwtverifier
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    {{- if .Values.authResolver.enabled }}
    - name: auth-resolver-metrics
      port: {{ .Values.authResolver.metrics.port }}
      targetPort: {{ .Values.authResolver.metrics.port }}
      protocol: TCP
    {{- end }}
  selector:
    app: jwtverifier
