---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: {{ .Values.externalSecretsWorkloadIdentityClientId }}
{{- range .Values.azureVaults }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name | default "default" }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .url | required "vault url is required" }}
{{- end}}

