apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-ca-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # depends on linkerd-ca secret
spec:
  ca:
    secretName: linkerd-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # depends on linkerd-ca-issuer
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-identity-trust-roots
  duration: 17500h0m0s
  renewBefore: 17000h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-anchor  # depends on linkerd-identity-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ca:
    secretName: linkerd-identity-trust-roots
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # depends on linkerd-trust-anchor
spec:
  secretName: linkerd-identity-issuer
  duration: 336h0m0s
  renewBefore: 168h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # depends on linkerd-identity-issuer
spec:
  sources:
    - secret:
        name: "linkerd-identity-trust-roots"
        key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
---          # below is the webhook certs --------------------------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-trust-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # depends on linkerd-ca-issuer
spec:
  isCA: true
  commonName: webhook.linkerd.cluster.local
  secretName: webhook-trust
  duration: 17500h0m0s
  renewBefore: 17000h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: webhook-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # depends on webhook-trust-issuer
spec:
  ca:
    secretName: webhook-trust
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # depends on webhook-issuer
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 336h0m0s
  renewBefore: 168h0m0s
  issuerRef:
    name: webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
  - linkerd-policy-validator.linkerd.svc
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # depends on webhook-issuer
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 336h0m0s
  renewBefore: 168h0m0s
  issuerRef:
    name: webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # depends on webhook-issuer
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 336h0m0s
  renewBefore: 168h0m0s
  issuerRef:
    name: webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
  - linkerd-sp-validator.linkerd.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---