{{- if (((.Values.trivy).podDisruptionBudget).operator).enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trivy-operator
  namespace: trivy-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # depends on trivy-operator namespace
spec:
  {{- if .Values.trivy.podDisruptionBudget.operator.minAvailable }}
  minAvailable: {{ .Values.trivy.podDisruptionBudget.operator.minAvailable }}
  {{- end }}
  {{- if .Values.trivy.podDisruptionBudget.operator.maxUnavailable }}
  maxUnavailable: {{ .Values.trivy.podDisruptionBudget.operator.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
{{- end }}