{{- if (.Values.rsaKey).generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rsaKey.secretName | default "rsa-key" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $privateKey := "" }}
{{- if .Release.IsUpgrade }}
  {{- $secretData := (get ((lookup "v1" "Secret" .Release.Namespace  "rsa-key" ) | default dict) "data")}}
  {{- $privateKey = (get $secretData "sig.pem" | b64dec ) | default "" }}
{{- end }}
{{- if not $privateKey }}
  {{- $privateKey = genPrivateKey "rsa" }}
{{- end }}
  sig.pem: |
    {{ $privateKey | b64enc }}
{{- end }}