apiVersion: v2
name: ingress-nginx
description: "Wrapper chart for installing ingress-nginx"
version: 4.11.5
maintainers:
  - name: Cloud Engineering, Bhagya Kandage
    email: bhagya.kandage@ifs.com
dependencies:
  - name: ingress-nginx
    version: 4.11.5
    repository: https://kubernetes.github.io/ingress-nginx
