apiVersion: v2
name: linkerd-crds
description: "Wrapper chart for installing linkerd-crds"
# renovate: datasource=helm depName=linkerd-crds registryUrl=https://helm.linkerd.io/stable
version: 1.8.0
maintainers:
  - name: Cloud Engineering, Bhagya Kandage
    email: bhagya.kandage@ifs.com
dependencies:
  - name: linkerd-crds
    version: 1.8.0
    repository: https://helm.linkerd.io/stable
