apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
  labels:
    app: health
spec:
  {{- if not (.Values.hpa).enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
        name: health
      annotations:
        {{- if .Values.podAnnotations }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity: {{ .Values.affinity | toYaml | nindent 12 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ .Values.topologySpreadConstraints | toYaml | nindent 12 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: health
        
          image: {{ .Values.imageRegistry }}/{{ .Values.imagePath }}:{{.Values.imageVersion}}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /v1/ping
              port: http
            initialDelaySeconds: 1
            periodSeconds: 10
          {{- if .Values.resources}}
          resources: {{ .Values.resources | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default "error" | quote }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          {{- if .Values.lifecycle }}
          lifecycle: {{ .Values.lifecycle | toYaml | nindent 12 }}
          {{- end }}
