apiVersion: v1
kind: Service
metadata:
  name: health
  labels:
    app: health
spec:
  type: ClusterIP
  selector:
    app: health
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
