apiVersion: v1
name: kyverno-policies-config
version: 0.1.11
maintainers:
  - name: SPO, Markus Sandin
    email: markus.sandin@ifs.com
description: |
  This bundle installs a set of Kyverno cluster policies listed below:
  - application-field-validation
  - application-prevent-app-of-apps-project
  - application-prevent-default-project
  - application-prevent-updates-project
  - applicationset-name-matches-project
  - check-ingress-annotation
  - check-limits-requests
  - disallow-default-namespace
  - disallow-ingress-auth-skip
  - disallow-latest-tag
  - inject-ingress-auth-headers
  - inject-ingress-service-upstream
  - limit-ingress-custom-snippets
  - pss-host-process
  - pss-host-namespaces
  - pss-privileged-containers
  - pss-capabilities
  - pss-hostpath-volumes
  - pss-host-ports
  - pss-apparmor
  - pss-selinux
  - pss-proc-mount-type
  - pss-seccomp
  - pss-sysctls
  - require-pod-probes
  - require-request-limits
  - restrict-image-registries
