{{ $settings := index .Values "jwk-provider" | default (dict) }}
{{- if $settings.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $settings.secretName | default "jwk-provider-rsa-key" }}
  namespace: platform
type: Opaque
data:
{{- $privateKey := "" }}
{{- if .Release.IsUpgrade }}
  {{- $secretData := (get ((lookup "v1" "Secret" .Release.Namespace  ($settings.secretName | default "jwk-provider-rsa-key") ) | default dict) "data")}}
  {{- $privateKey = (get $secretData "sig.pem" | b64dec ) | default "" }}
{{- end }}
{{- if not $privateKey }}
  {{- $privateKey = genPrivateKey "rsa" }}
{{- end }}
  sig.pem: |
    {{ $privateKey | b64enc }}
{{- end }}