{{- $settings := index (.Values.argocd | default (dict)) "application-prevent-default-project" | default (dict) }}
{{- if and (.Values.argocd).enabled (or $settings.enabled (and (not (hasKey $settings "enabled")) .Values.default.enabled)) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: application-prevent-default-project
  annotations:
    policies.kyverno.io/title: Prevent Use of Default Project
    policies.kyverno.io/category: Argo
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Application
    policies.kyverno.io/description: >-
      This policy prevents the use of the default project in an Application.
spec:
  validationFailureAction: {{ default .Values.default.validationFailureAction $settings.validationFailureAction }}
  failurePolicy: {{ default .Values.default.failurePolicy $settings.failurePolicy }}
  admission: {{ default .Values.default.admission $settings.admission }}
  background: {{ default .Values.default.background $settings.background }}
  rules:
    - name: default-project
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Application
      preconditions:
        all:
          - key: "{{ "{{ request.operation || 'BACKGROUND' }}" }}"
            operator: NotEquals
            value: DELETE
      validate:
        allowExistingViolations: true
        message: "The default project may not be used in an Application."
        pattern:
          spec:
            project: "!default"
{{- end}}
