{{- $settings := index (.Values.general | default (dict)) "disallow-latest-tag" | default (dict) }}
{{- if or $settings.enabled (and (not (hasKey $settings "enabled")) .Values.default.enabled) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    general.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the 
      image changes. A best practice is to use an immutable tag that maps to 
      a specific version of an application pod.
spec:
  validationFailureAction: {{ default .Values.default.validationFailureAction $settings.validationFailureAction }}
  failurePolicy: {{ default .Values.default.failurePolicy $settings.failurePolicy }}
  admission: {{ default .Values.default.admission $settings.admission }}
  background: {{ default .Values.default.background $settings.background }}
  rules:
    - name: require-image-tag
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Pod
      {{- include "exclusions" $settings | nindent 6 }}
      preconditions:
        all:
          - key: "{{ "{{ request.operation || 'BACKGROUND' }}" }}"
            operator: NotEquals
            value: DELETE
      validate:
        allowExistingViolations: true
        message: "An image tag is required."
        pattern:
          spec:
            containers:
              - image: "*:*"
    - name: validate-image-tag
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Pod
      {{- if $settings.exclude }}
      exclude:
        {{- toYaml $settings.exclude | nindent 8 }}
      {{- end}}
      preconditions:
        all:
          - key: "{{ "{{ request.operation || 'BACKGROUND' }}" }}"
            operator: NotEquals
            value: DELETE
      validate:
        allowExistingViolations: true
        message: "Using a mutable image tag e.g. 'latest' is not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"

{{- end}}

